var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/accessibility/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0s9_cet._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_1kf02sq.js")
R.c("server/chunks/ssr/[root-of-the-server]__0t1wu3z._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1fax1sl._.js")
R.c("server/chunks/ssr/_0e_29i-._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0-o-goa.js")
R.c("server/chunks/ssr/_next-internal_server_app_accessibility_page_actions_0fcn21a.js")
R.m(56100)
module.exports=R.m(56100).exports
