var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/products/[slug]/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0ahb-a6._.js")
R.c("server/chunks/ssr/_1bphtpw._.js")
R.c("server/chunks/ssr/node_modules_0x60bxo._.js")
R.c("server/chunks/ssr/lib_backend_catalog_ts_094-vg6._.js")
R.c("server/chunks/ssr/_125fd6r._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0x74gh2.js")
R.c("server/chunks/ssr/[root-of-the-server]__0t1wu3z._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1fax1sl._.js")
R.c("server/chunks/ssr/_0e_29i-._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0-o-goa.js")
R.c("server/chunks/ssr/_next-internal_server_app_products_[slug]_page_actions_1x_s7mf.js")
R.m(8184)
module.exports=R.m(8184).exports
