var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/checkout/route.js")
R.c("server/chunks/lib_backend_catalog_ts_00qnv5u._.js")
R.c("server/chunks/_0ruou2l._.js")
R.c("server/chunks/[root-of-the-server]__1b2taul._.js")
R.c("server/chunks/node_modules_@supabase_supabase-js_dist_index_mjs_0u-n9p7._.js")
R.c("server/chunks/[root-of-the-server]__0xuaoik._.js")
R.c("server/chunks/[root-of-the-server]__1cmfuie._.js")
R.c("server/chunks/node_modules_zod_v3_external_1pf3m_7.js")
R.c("server/chunks/_next-internal_server_app_api_checkout_route_actions_0jrgp1c.js")
R.m(63437)
module.exports=R.m(63437).exports
