// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/about" | "/accessibility" | "/account" | "/admin" | "/cart" | "/checkout" | "/checkout/cancel" | "/checkout/success" | "/collection" | "/collections" | "/contact" | "/journal" | "/privacy" | "/products/[slug]" | "/returns" | "/services" | "/shipping" | "/terms"
type AppRouteHandlerRoutes = "/api/account" | "/api/account/addresses" | "/api/account/addresses/[id]" | "/api/account/profile" | "/api/admin" | "/api/admin/access" | "/api/admin/access/[id]" | "/api/admin/bootstrap" | "/api/admin/content" | "/api/admin/inventory" | "/api/admin/inventory/[id]" | "/api/admin/login-identity" | "/api/admin/media" | "/api/admin/orders" | "/api/admin/orders/[id]/status" | "/api/admin/products" | "/api/admin/settings" | "/api/admin/social-links" | "/api/checkout" | "/api/delivery/quote" | "/api/health" | "/api/inventory/[slug]" | "/api/notifications/process" | "/api/orders" | "/api/products" | "/api/products/[slug]" | "/api/stripe/webhook"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/about": {}
  "/accessibility": {}
  "/account": {}
  "/admin": {}
  "/api/account": {}
  "/api/account/addresses": {}
  "/api/account/addresses/[id]": { "id": string; }
  "/api/account/profile": {}
  "/api/admin": {}
  "/api/admin/access": {}
  "/api/admin/access/[id]": { "id": string; }
  "/api/admin/bootstrap": {}
  "/api/admin/content": {}
  "/api/admin/inventory": {}
  "/api/admin/inventory/[id]": { "id": string; }
  "/api/admin/login-identity": {}
  "/api/admin/media": {}
  "/api/admin/orders": {}
  "/api/admin/orders/[id]/status": { "id": string; }
  "/api/admin/products": {}
  "/api/admin/settings": {}
  "/api/admin/social-links": {}
  "/api/checkout": {}
  "/api/delivery/quote": {}
  "/api/health": {}
  "/api/inventory/[slug]": { "slug": string; }
  "/api/notifications/process": {}
  "/api/orders": {}
  "/api/products": {}
  "/api/products/[slug]": { "slug": string; }
  "/api/stripe/webhook": {}
  "/cart": {}
  "/checkout": {}
  "/checkout/cancel": {}
  "/checkout/success": {}
  "/collection": {}
  "/collections": {}
  "/contact": {}
  "/journal": {}
  "/privacy": {}
  "/products/[slug]": { "slug": string; }
  "/returns": {}
  "/services": {}
  "/shipping": {}
  "/terms": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
