var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/account/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__1d44bz1._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_1g9aalh.js")
R.c("server/chunks/ssr/[root-of-the-server]__0t1wu3z._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1fax1sl._.js")
R.c("server/chunks/ssr/_0e_29i-._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0-o-goa.js")
R.c("server/chunks/ssr/_next-internal_server_app_account_page_actions_1n6f9-s.js")
R.m(7242)
module.exports=R.m(7242).exports
