var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/returns/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0olirl1._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0k87tem.js")
R.c("server/chunks/ssr/[root-of-the-server]__0t1wu3z._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1fax1sl._.js")
R.c("server/chunks/ssr/_0e_29i-._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0-o-goa.js")
R.c("server/chunks/ssr/_next-internal_server_app_returns_page_actions_0e4j08y.js")
R.m(66175)
module.exports=R.m(66175).exports
